blank_issues_enabled: false
contact_links:
  - name: Mod Discord
    url: https://discord.gg/wuamm4P
    about: If you are not sure about something, ask on Discord
  - name: Vampirism Integrations
    url: https://github.com/TeamLapen/VampirismIntegrations
    about: Request integration with other mods here (No bugreports)