---
name: General enhancement/TODO
about: Don't use, unless suggest something unrelated to mod functionality (like mod documentation or codestyle)
title: ''
labels: unconfirmed, TODO
assignees: ''

---
Don't use if any other template is suitable.
This is mainly for internal use.

Describe what is missing.
