name: Gradle Build

on:
  push:
    branches:
      - 'dev'
      - '1.20*'
      - 'feature/*'
  pull_request:
    branches:
      - 'dev'
      - '1.20*'
      - 'feature/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Gradle
        run: ./gradlew
      - name: Build
        run: ./gradlew build
