name: Update API

on:
  push:
    paths:
      - '**/src/main/resources/supporters.json'
      - '**/src/main/resources/default_remote_config.json'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - uses: actions/checkout@v3
      - name: Upload supporters
        uses: wei/curl@v1
        with:
          args: |
            -X 'POST' 'https://api.vampirism.dev/api/v1/supporter/set' -H 'x-api-key: ${{ secrets.VAMPIRISM_API }}' -H 'Content-Type: application/json' --upload-file src/main/resources/supporters.json
      - name: Upload settings
        uses: wei/curl@v1
        with:
          args: |
            -X 'POST' 'https://api.vampirism.dev/api/v1/config/set' -H 'x-api-key: ${{ secrets.VAMPIRISM_API }}' -H 'Content-Type: application/json' --upload-file src/main/resources/default_remote_config.json
